plugins:
  - jekyll-remote-theme  # 启用远程主题插件
  - jekyll-seo-tag       # 可选：SEO优化插件（GitHub Pages默认支持）
  - jekyll-feed          # 可选：RSS订阅插件
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
